# Generated by Django 4.1.2 on 2022-11-25 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название заявки')),
                ('content', models.TextField(blank=True, verbose_name='Описание заявки')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('photo_after', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фотография заявки после')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фотография заявки')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создание заявки')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения заявки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('status', models.CharField(choices=[('CREATED', 'Новая заявка'), ('AGREED', 'Заявка решена'), ('REJECTED', 'Заявка отклонена')], default='CREATED', max_length=30, verbose_name=users.models.Status)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicationCategory', to='users.category', verbose_name='Категория')),
                ('user', models.ManyToManyField(related_name='applicationUser', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
                'ordering': ['status'],
            },
        ),
    ]
