# Generated by Django 4.1.2 on 2022-12-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_afterphoto_application_pa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='photo_after',
        ),
    ]
